# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07375a2251566b65bf4d4b80362e88fed4033522b51fbe850365811c93d9f732754b9ad83c7897b9be9a058638bf02beb926cb29bcb6b4bce461a06046fe847e

test:
  secret_key_base: 1ae089dd42f852765d670ca710efbca096fea7f4ac74ad082613577b6e5535c9a214712f74a38e13ea6509a62d099e34f0219b1aab0b274f008ff573e16c2dd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
